# Generated by Django 6.1 on 2026-09-13 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.PositiveSmallIntegerField(help_text='Tahun project dikerjakan atau dimulai.')),
                ('category', models.CharField(choices=[('competition', 'Competition'), ('academic', 'Academic'), ('organization', 'Organization'), ('personal', 'Personal')], default='personal', max_length=20)),
                ('technologies', models.CharField(blank=True, help_text='Daftar teknologi dipisahkan koma, contoh: Django, React, Figma.', max_length=255)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', '-year', 'title'],
            },
        ),
    ]
