# Generated by Django 6.1 on 2026-09-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('competition', 'Competition'), ('organization', 'Organization'), ('academic', 'Academic')], default='personal', max_length=20),
        ),
    ]
